// <auto-generated />
using System;
using EmployeeManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManager.WebAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127164315_CountryAndJobCategorySeed")]
    partial class CountryAndJobCategorySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("EmployeeManager.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("EmployeeManager.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 16,
                            Name = "France"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 35,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 41,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 50,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Vatican City"
                        });
                });

            modelBuilder.Entity("EmployeeManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuperiorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("SuperiorId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeManager.Models.EmployeeJobCategory", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId", "JobCategoryId");

                    b.HasIndex("JobCategoryId");

                    b.ToTable("EmployeeJobCategories");
                });

            modelBuilder.Entity("EmployeeManager.Models.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Product Manager"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Project Manager"
                        },
                        new
                        {
                            Id = 4,
                            Title = "QA Engineer"
                        },
                        new
                        {
                            Id = 5,
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            Id = 6,
                            Title = "HR Specialist"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Sales Representative"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Marketing Manager"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Business Analyst"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Customer Support"
                        });
                });

            modelBuilder.Entity("EmployeeManager.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("EmployeeManager.Models.Address", b =>
                {
                    b.HasOne("EmployeeManager.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("EmployeeManager.Models.Employee", b =>
                {
                    b.HasOne("EmployeeManager.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManager.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManager.Models.Employee", "Superior")
                        .WithMany("Subordinates")
                        .HasForeignKey("SuperiorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");

                    b.Navigation("Country");

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("EmployeeManager.Models.EmployeeJobCategory", b =>
                {
                    b.HasOne("EmployeeManager.Models.Employee", "Employee")
                        .WithMany("EmployeeJobCategories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManager.Models.JobCategory", "JobCategory")
                        .WithMany("EmployeeJobCategories")
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("EmployeeManager.Models.Salary", b =>
                {
                    b.HasOne("EmployeeManager.Models.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManager.Models.Employee", b =>
                {
                    b.Navigation("EmployeeJobCategories");

                    b.Navigation("Salaries");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("EmployeeManager.Models.JobCategory", b =>
                {
                    b.Navigation("EmployeeJobCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
