/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDtoId } from './addressDtoId';


export interface CountryDto { 
    id?: AddressDtoId;
    name?: string;
}

