/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryDto } from './salaryDto';
import { AddressDtoId } from './addressDtoId';
import { AddressDto } from './addressDto';
import { EmployeeGetDtoSuperiorId } from './employeeGetDtoSuperiorId';
import { JobCategoryDto } from './jobCategoryDto';


export interface EmployeeGetDto { 
    id?: AddressDtoId;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    birthDate?: string;
    gender?: string;
    address?: AddressDto | null;
    countryId?: AddressDtoId;
    email?: string;
    phoneNumber?: string | null;
    joinedDate?: string;
    exitedDate?: string | null;
    superiorId?: EmployeeGetDtoSuperiorId | null;
    salary?: SalaryDto | null;
    jobCategories?: Array<JobCategoryDto>;
}

