/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeListDto { 
    id?: any | null;
    firstName?: string;
    lastName?: string;
    email?: string;
    phoneNumber?: string | null;
    birthDate?: string;
    joinedDate?: string;
}

