/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CountryDtoId } from './countryDtoId';
import { EmployeeGetDtoSuperiorId } from './employeeGetDtoSuperiorId';


export interface EmployeeGetDto { 
    id?: CountryDtoId;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    birthDate?: string;
    gender?: string;
    addressId?: CountryDtoId;
    countryId?: CountryDtoId;
    email?: string;
    phoneNumber?: string | null;
    joinedDate?: string;
    exitedDate?: string | null;
    superiorId?: EmployeeGetDtoSuperiorId | null;
}

