/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';
import { JobCategoryDto } from './jobCategoryDto';


export interface EmployeeUpdateDto { 
    id?: any | null;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    birthDate?: string;
    gender?: string;
    address?: AddressDto | null;
    countryId?: any | null;
    email?: string;
    phoneNumber?: string | null;
    joinedDate?: string;
    exitedDate?: string | null;
    superiorId?: any | null;
    salary?: any | null;
    jobCategories?: Array<JobCategoryDto>;
}

