/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryDto } from './salaryDto';
import { CountryDto } from './countryDto';
import { EmployeeSummaryDto } from './employeeSummaryDto';
import { AddressDto } from './addressDto';
import { JobCategoryDto } from './jobCategoryDto';


export interface EmployeeDetailDto { 
    id?: any | null;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    birthDate?: string;
    gender?: string;
    address?: AddressDto | null;
    country?: CountryDto;
    email?: string;
    phoneNumber?: string | null;
    joinedDate?: string;
    exitedDate?: string | null;
    superior?: EmployeeSummaryDto | null;
    subordinates?: Array<EmployeeSummaryDto>;
    salary?: SalaryDto | null;
    salaries?: Array<SalaryDto>;
    jobCategories?: Array<JobCategoryDto>;
}

