/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CountryDtoId } from './countryDtoId';


export interface JobCategoryDto { 
    id?: CountryDtoId;
    title?: string;
}

