/**
 * EmployeeManager.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryDtoAmount } from './salaryDtoAmount';
import { AddressDtoId } from './addressDtoId';


export interface SalaryDto { 
    id?: AddressDtoId;
    amount?: SalaryDtoAmount;
    from?: string;
    to?: string | null;
}

